BEGIN;

CREATE DOMAIN "email" AS text CHECK (
    value ~ '^[a-zA-Z0-9.!#$%&''*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$'
);

DROP TABLE IF EXISTS "user", "stretch", "role", "category";

CREATE TABLE
    IF NOT EXISTS "user" (
        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "email" email NOT NULL UNIQUE,
        "password" VARCHAR NOT NULL ,
        "username" VARCHAR(15) NOT NULL,
        "biography" VARCHAR(255),
        "favorites" INTEGER[],
        "role_id" INTEGER NOT NULL,
    );

CREATE TABLE
    IF NOT EXISTS "stretch" (
        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "title" VARCHAR(255) NOT NULL NOT NULL,
        "description_content" VARCHAR NOT NULL,
        "main_image" VARCHAR,
        "description_image" VARCHAR,
        "category_id"
    );

CREATE TABLE
    IF NOT EXISTS "role" (
        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "label" INTEGER,
        /*  "user" INTEGER NOT NULL CHECK ("user" IN (1)),
        "admin" INTEGER NOT NULL CHECK ("admin" IN (2)),
    CONSTRAINT unique_user_admin UNIQUE ("user", "admin")*/
);

CREATE TABLE
    IF NOT EXISTS "category" (
        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" VARCHAR(255) NOT NULL,
    );
    
COMMIT;
